### ISSUE TITLE
What is the right way to close connection to server

### ISSUE THREAD

**Issue by KrishnaPG** [numtel/meteor-mysql#7] opened 2015-02-19 08:25 UTC
I am seeing too many connections on the server. Most of the times when meteor is rebuilding the app, the old connections are staying there increasing the thread-count on the server and wasting resources. What is the right way to `close these connections` after client disconnect (either within code or through some `configuration setting`)?

I would like to have no more than 10 threads/connections idle and any other new threads created should wait for a max of 5 minutes and close the connection. How to achieve it? Right now, I have 133 threads below created and aborted by client
![image](https://cloud.githubusercontent.com/assets/4610831/6263467/52b5cf82-b83e-11e4-98a0-6a0576c765e6.png)

**Comment by KrishnaPG** [comment] 2015-02-20 13:08
Never mind, found this online tool to generate my.cnf file automatically based on input https://tools.percona.com/wizard Sharing it here just so others can also benefit. Thank you.

**Comment by KrishnaPG** [comment] 2015-02-20 13:53
Actually the configurations does not deal with closing the idle connections - perhaps we should figure a way of closing the connections once the publishing is done or on some time out.

**Comment by numtel** [comment] 2015-02-21 05:11
Hmm this is an interesting issue that I had not thought about. When Meteor does a hot code push, refreshing the server, the application is not notified. 

In order to not send duplicate result sets on server restarts, I had to add a DDP message to reset the client side results before sending the initial results. But this requires no knowledge of whether the server was restarting, it runs on all initializations.

I'm not sure of any way to tell from inside the application when Meteor decides to restart. It must be possibile somehow. I definitely agree that this is a major issue.

**Comment by numtel** [comment] 2015-02-25 03:50
I have determined that this is not a bug but in fact, simply a matter of adding the necessary code to close connections on exit to your application.

On the server-side of your Meteor app add the following event handler:

```javascript
var liveDb = new LiveMysql(Meteor.settings.mysql);

process.on('SIGTERM', function() {
  liveDb.end();
  process.exit();
});
```

I cannot add this code to the library directly because you can only effectively have one listener on the `SIGTERM` event per application. I will be adding this code the readme though.

Thanks for the issue, please let me know of any more you come across. :smile:

**Comment by numtel** [comment] 2015-02-25 04:01
Wait a second...that doesn't quite work. Seems to be a bug with Zongji.

**Comment by numtel** [comment] 2015-02-25 05:21
@KrishnaPG I've just made the pull request for this bug on Zongji. I will release a new version as soon as the updated zongji module is released.

**Comment by KrishnaPG** [comment] 2015-02-25 05:57
Cool - thanks for addressing this @numtel . This certainly will improve overall usability of the package and certainly will save resources on shared hosting infrastructures.

**Comment by KrishnaPG** [comment] 2015-02-25 06:03
BTW, I hope this fix in zongji, takes the scenario of multiple clients into consideration. I am not an expert on binlog or mysql - but just in case there are multiple meteor clients for the same server and one client goes away - hope this *killing the binlog* does not affect the other connected clients (who may still need that binlog for updates).

In other words, if mysql's binlog is in one-one relation with clients, the fix of killing it may be fine. Otherwise, if binlog is 1-to-many, then we may have to let it run till all other clients are done.

**Comment by numtel** [comment] 2015-02-25 10:13
@KrishnaPG Don't worry, your clients will be safe :sunglasses:

**Comment by numtel** [comment] 2015-02-27 23:19
@KrishnaPG Ok this is now fixed and I have updated the leaderboard example application to illustrate how to close connections on code push and exit (ctrl+c).

You will need to be updated to the latest version of this package, 0.1.3, for this to work.

https://github.com/numtel/meteor-mysql-leaderboard/blob/master/leaderboard.js#L73-80

```javascript
  var closeAndExit = function() {
    liveDb.end();
    process.exit();
  };
  // Close connections on hot code push
  process.on('SIGTERM', closeAndExit);
  // Close connections on exit (ctrl + c)
  process.on('SIGINT', closeAndExit);
```

**Closed by numtel** 2015-02-27 23:19 UTC
Labels: bug, question

**Comment by KrishnaPG** [comment] 2015-02-28 04:00
Cool - thanks. This looks good.
